build_from:
  amd64: python:3.13-alpine3.21
  aarch64: python:3.13-alpine3.21
  armv7: python:3.13-alpine3.21
  armhf: python:3.13-alpine3.21
  i386: python:3.13-alpine3.21
labels:
  org.opencontainers.image.title: "Claude Code for Home Assistant"
  org.opencontainers.image.description: "Claude Code CLI with web terminal and HA integration"
  org.opencontainers.image.source: "https://github.com/robsonfelix/robsonfelix-hass-addons"
  org.opencontainers.image.licenses: "MIT"
